### ISSUE TITLE
Add VCV modular synth support

### ISSUE THREAD

**Issue by oubiwann** [ut-proj/undermidi#38]
## Features / Tasks

* [x] Investigate interop to determine if any new MIDI CC messages need to be supported
* [x] Experiment with existing MIDI CC support to see if any VCV Rack-specific convenience functions / macros are warranted
* [x] Add the ability to send realtime messages to the Go midiserver (and thus to VCV Rack)
* [ ] Add a beat state machine
  * [ ] create a new gen_server whose managed state will track clock ticks (simple counter / incrementer)
  * [ ] init args should include time signature info
  * [ ] support changes to time signature while running
  * [ ] calculate BPM, beats per measure, current measure, current beat
  * [ ] support sending MIDI messages, leaving room/time for message transmission (should be delivered before the target beat, but after the beat prior to the target beat) 
    * [ ] at a given beat by absolute count
    * [ ] at a given beat for a given measure
    * [ ] at next beat
    * [ ] at next nth beat of the next measure
    * [ ] at next nth beat of the next nth measure

## Resourrces

VCV is a free, open source modular synthesis framework (Eurorack emulator): 
* https://vcvrack.com/
* https://vcvrack.com/manual/
* https://library.vcvrack.com/
* http://www.studiobrootle.com/best-vcv-rack-modules/

Specific support: MIDI control of the synth. See the MIDI plugins for more details:
* https://library.vcvrack.com/?query=&brand=VCV&tag=MIDI&license=free

Original issue created here:
* https://github.com/ut-proj/undertone/issues/65

**Comment by oubiwann** [comment]
I'm going to turn this into an epic, since there's a fair amount that needs to be done in order to support useful control of VCV Rack (with LFE as a  compositional tool for the modular synth).

**Comment by oubiwann** [comment]
I've performed basic VCV control from LFE today using this demo patch:
* https://github.com/forgotten-tones/vcv/blob/main/patches/midi/lfe-undermidi-00.vcv

**Comment by oubiwann** [comment]
This got closed automatically -- reopening ....
