### ISSUE TITLE
Migrate from Go to Erlang NIF

### ISSUE THREAD

**Issue by oubiwann** [ut-proj/undermidi#52]
This work will take place in a separate branch, based off of the latest release branch. If the work is successful and preferred to the Go solution, it will become the next release branch.

High-level tasks that need to be completed first include:
* [x] Create new epic branch
* [x] Update CI/CD with the latest and ensure that current code still works
* [x] ❌ ut-proj/midiserver#40
  * [ ] Does the [rebar3 plugin](https://github.com/rusterlium/rebar3_cargo) support rustler-precompiled?
* [x] ❌ Explore the process of creating an Erlang API wrapping Rust bindings with Rustler, e.g.:
  * [x] https://medium.com/@brucifi/writing-your-first-erlang-nif-in-rust-274374094207
  * [x] https://github.com/haubie/midiex/blob/main/lib/midiex/backend.ex
* [x] ut-proj/midiserver#41

Lower-level tasks:
* [x] ut-proj/midiserver#43
* [x] Update deps, etc.
* [x] Remove all old code referencing midiserver, Go, erlexec, etc.
* [x] #56
* [x] #57
* [x] #58
* [x] #53
* [ ] #59

Enhancements/cleanup:
* [x] When using the rebar3 profile + alias `rebar3 as undermidi repl`, ensure that undermidi is started automatically
* [x] When starting undermidi automatically (or with that `repl` alias), replace the LFE banner with the undermidi one

Final epic tasks:
* [x] Update `LICENSE` with notes about pulled in software (Sonic Pi Erlang, C/C++, etc.)
* [ ] ❌ Update copied files with file header comments for attribution/license (code not included; it's downloaded via git)
* [ ] Evaluate effort for level of success/future viability
* [ ] ❌ Create new repo for old code, e.g., `midiserver-go`, and push `main` there for easy reference/use (the old repo was moved out of ut-proj, back to geomyidia)
* [ ] ❌ Update logo (Liffybot?!), merge epic to `main`, cut release, push to hex.pm

**Comment by oubiwann** [comment]
I think the goal of this epic has been fully satisfied -- the remaining work that is to be done or is in progress, can be decoupled from this particular effort.
